version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: write-note
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: adminsecret
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - laravel
  app:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8000:8000"
    volumes:
      - ./api:/var/www/html
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  mysql-data:
